<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class UniversitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $emailCsvPath = database_path('seeders/data/DATA_UNIV_EMAIL_LENGKAP.csv');
        
        // Baca file email untuk mapping
        $emailMapping = [];
        if (file_exists($emailCsvPath)) {
            if (($emailHandle = fopen($emailCsvPath, 'r')) !== false) {
                $emailHeader = fgetcsv($emailHandle, 0, ',');
                while (($emailRow = fgetcsv($emailHandle, 0, ',')) !== false) {
                    if (count($emailRow) >= 3) {
                        $emailData = array_combine($emailHeader, $emailRow);
                        $univName = trim($emailData['Nama Perguruan Tinggi'] ?? '');
                        $email = trim($emailData['Email Resmi / Humas'] ?? '');
                        if (!empty($univName)) {
                            $emailMapping[$univName] = (!empty($email)) ? $email : '-';
                        }
                    }
                }
                fclose($emailHandle);
            }
        }
        
        // Update email untuk universitas yang sudah ada
        $this->command->info("Updating university emails...");
        $updated = 0;
        foreach ($emailMapping as $univName => $email) {
            $result = DB::table('universities')
                ->where('name', $univName)
                ->update(['email' => $email, 'updated_at' => Carbon::now()]);
            if ($result) {
                $updated++;
            }
        }
        $this->command->info("Updated {$updated} universities with email data");
        
        // Data universitas hanya untuk referensi - tidak digunakan lagi
        // Hanya update email saja, tidak insert data baru
        /* $universities = [
            ['name' => 'Universitas Nusa Cendana', 'code' => 'UNDANA'],
            ['name' => 'Universitas Fajar', 'code' => 'UNIFA'],
            ['name' => 'Universitas Merdeka Surabaya', 'code' => 'UNMERBAYA'],
            ['name' => 'Universitas Teknologi Yogyakarta', 'code' => 'UTY'],
            ['name' => 'Universitas Diponegoro', 'code' => 'UNDIP'],
            ['name' => 'Universitas Pendidikan Indonesia', 'code' => 'UPI'],
            ['name' => 'Universitas Malikussaleh', 'code' => 'UNIMAL'],
            ['name' => 'Institut Modern Arsitektur Dan Teknologi', 'code' => 'IMAT'],
            ['name' => 'Universitas Sumatera Utara', 'code' => 'USU'],
            ['name' => 'Institut Sains Dan Teknologi TD Pardede', 'code' => 'ISTP'],
            ['name' => 'Universitas Mpu Tantular', 'code' => 'UMT'],
            ['name' => 'Universitas Prisma', 'code' => 'UNPRIS'],
            ['name' => 'Universitas Nusa Nipa', 'code' => 'UNIPA'],
            ['name' => 'Universitas Hasanuddin', 'code' => 'UNHAS'],
            ['name' => 'Institut Teknologi Kalimantan', 'code' => 'ITK'],
            ['name' => 'Sekolah Tinggi Ilmu Teknik Trisula', 'code' => 'STIT Trisula'],
            ['name' => 'Universitas Nahdlatul Ulama Kalimantan Selatan', 'code' => 'UNUKASE'],
            ['name' => 'Universitas Pandanaran', 'code' => 'UNPAND'],
            ['name' => 'Universitas Bina Taruna Gorontalo', 'code' => 'UNBITA'],
            ['name' => 'Universitas Nahdlatul Ulama Gorontalo', 'code' => 'UNUGO'],
            ['name' => 'Universitas Ichsan Gorontalo', 'code' => 'UNISAN'],
            ['name' => 'Universitas Negeri Makassar', 'code' => 'UNM'],
            ['name' => 'Universitas Nahdlatul Ulama Kalimantan Timur', 'code' => 'UNUKALTARA'],
            ['name' => 'Universitas Negeri Gorontalo', 'code' => 'UNG'],
            ['name' => 'Universitas Atma Jaya Yogyakarta', 'code' => 'UAJY'],
            ['name' => 'Universitas Internasional Batam', 'code' => 'UIB'],
            ['name' => 'Universitas Islam Negeri Walisongo Semarang', 'code' => 'UIN Walisongo'],
            ['name' => 'Universitas Kristen Indonesia', 'code' => 'UKI'],
            ['name' => 'Universitas Bina Nusantara', 'code' => 'BINUS'],
            ['name' => 'Universitas Widya Mataram', 'code' => 'UWMY'],
            ['name' => 'Universitas Katolik Parahyangan', 'code' => 'UNPAR'],
            ['name' => 'Universitas Kristen Maranatha', 'code' => 'UKM'],
            ['name' => 'Universitas Selamat Sri', 'code' => 'UNISS'],
            ['name' => 'Politeknik Negeri Pontianak', 'code' => 'POLNEP'],
            ['name' => 'Institut Teknologi Sumatera', 'code' => 'ITERA'],
            ['name' => 'Universitas Katolik Soegijapranata', 'code' => 'UNIKA Soegijapranata'],
            ['name' => 'Institut Teknologi Minaesa', 'code' => 'ITM'],
            ['name' => 'Universitas 17 Agustus 1945 Semarang', 'code' => 'UNTAG Semarang'],
            ['name' => 'Universitas Syiah Kuala', 'code' => 'USK'],
            ['name' => 'Universitas Ibrahimy', 'code' => 'UNIB'],
            ['name' => 'Institut Teknologi Garut', 'code' => 'ITG'],
            ['name' => 'Universitas Tomakaka', 'code' => 'UNIV. TOMAKAKA'],
            ['name' => 'Universitas Agung Podomoro', 'code' => 'UAP'],
            ['name' => 'Universitas Indonesia', 'code' => 'UI'],
            ['name' => 'Institut Teknologi Calvin', 'code' => 'ITC'],
            ['name' => 'Universitas Nusantara Manado', 'code' => 'UNSAT'],
            ['name' => 'Universitas Quality Berastagi', 'code' => 'UQB'],
            ['name' => 'Universitas Bhinneka PGRI', 'code' => 'UBHARA'],
            ['name' => 'Institut Teknologi Sepuluh Nopember', 'code' => 'ITS'],
            ['name' => 'Universitas Gunadarma', 'code' => 'UG'],
            ['name' => 'Universitas Muhammadiyah Surakarta', 'code' => 'UMS'],
            ['name' => 'Universitas Ekasakti', 'code' => 'UNES'],
            ['name' => 'Universitas Lancang Kuning', 'code' => 'UNILAK'],
            ['name' => 'Universitas Sam Ratulangi', 'code' => 'UNSRAT'],
            ['name' => 'Sekolah Tinggi Arsitektur YKPN Yogyakarta', 'code' => 'STARS YKPN'],
            ['name' => 'Universitas Muhammadiyah Aceh', 'code' => 'UNMUHA'],
            ['name' => 'Universitas Presiden', 'code' => 'PRESIDENT UNIVERSITY'],
            ['name' => 'Institut Seni Indonesia Surakarta', 'code' => 'ISI Surakarta'],
            ['name' => 'Universitas Prima Indonesia', 'code' => 'UNPRI'],
            ['name' => 'Universitas Brawijaya', 'code' => 'UB'],
            ['name' => 'Institut Sains Dan Teknologi Nasional', 'code' => 'ISTN'],
            ['name' => 'Universitas Kristen Duta Wacana', 'code' => 'UKDW'],
            ['name' => 'Universitas Yapis Papua', 'code' => 'UNIYAP'],
            ['name' => 'Politeknik Negeri Sriwijaya', 'code' => 'POLSRI'],
            ['name' => 'Institut Teknologi Bandung', 'code' => 'ITB'],
            ['name' => 'Institut Teknologi Bacharuddin Jusuf Habibie', 'code' => 'ITH'],
            ['name' => 'Universitas Al Washliyah Darussalam Banda Aceh', 'code' => 'UNIVA'],
            ['name' => 'Universitas Madani', 'code' => 'UMDA'],
            ['name' => 'Universitas Sebelas Maret', 'code' => 'UNS'],
            ['name' => 'Universitas Borobudur', 'code' => 'UNBOR'],
            ['name' => 'Universitas Udayana', 'code' => 'UNUD'],
            ['name' => 'Universitas Warmadewa', 'code' => 'UNWAR'],
            ['name' => 'Universitas Muhammadiyah Bengkulu', 'code' => 'UMB'],
            ['name' => 'Universitas Negeri Manado', 'code' => 'UNIMA'],
            ['name' => 'Universitas Tunas Pembangunan Surakarta', 'code' => 'UTP'],
            ['name' => 'Universitas Langlang Buana', 'code' => 'UNLA'],
            ['name' => 'Universitas Merdeka Malang', 'code' => 'UNMER Malang'],
            ['name' => 'Universitas Tribhuwana Tungga Dewi', 'code' => 'UNITRI'],
            ['name' => 'Universitas Persada Indonesia Yai', 'code' => 'UPI Y.A.I'],
            ['name' => 'Universitas Pelita Harapan', 'code' => 'UPH'],
            ['name' => 'Universitas Islam Negeri Sunan Ampel', 'code' => 'UINSA'],
            ['name' => 'Universitas Islam Negeri Datokarama Palu', 'code' => 'UIN Datokarama'],
            ['name' => 'Institut Pertanian Bogor', 'code' => 'IPB'],
            ['name' => 'Universitas Matana', 'code' => 'UM'],
            ['name' => 'Universitas Medan Area', 'code' => 'UMA'],
            ['name' => 'Universitas Negeri Medan', 'code' => 'UNIMED'],
            ['name' => 'Universitas Islam Indonesia', 'code' => 'UII'],
            ['name' => 'Universitas Ubudiyah Indonesia', 'code' => 'UUI'],
            ['name' => 'Universitas Lambung Mangkurat', 'code' => 'ULM'],
            ['name' => 'Universitas Indo Global Mandiri', 'code' => 'UIGM'],
            ['name' => 'Universitas Faletehan', 'code' => 'UF'],
            ['name' => 'Universitas Madako Tolitoli', 'code' => 'UMTOL'],
            ['name' => 'Universitas Subang', 'code' => 'UNSUB'],
            ['name' => 'Institut Teknologi Adhi Tama Surabaya', 'code' => 'ITATS'],
            ['name' => 'Universitas Multimedia Nusantara Jakarta', 'code' => 'UMN'],
            ['name' => 'Universitas Tridinanti', 'code' => 'UNTRI'],
            ['name' => 'Universitas Islam Negeri Sulthan Thaha Saifuddin Jambi', 'code' => 'UIN STS Jambi'],
            ['name' => 'Universitas Kristen Petra', 'code' => 'UK Petra'],
            ['name' => 'Universitas Katolik Darma Cendika', 'code' => 'UKDC'],
            ['name' => 'Universitas Krisnadwipayana', 'code' => 'UNKRIS'],
            ['name' => 'Universitas Lampung', 'code' => 'UNILA'],
            ['name' => 'Universitas Jayabaya', 'code' => 'UJ'],
            ['name' => 'Universitas Negeri Yogyakarta', 'code' => 'UNY'],
            ['name' => 'Institut Desain Dan Bisnis Bali', 'code' => 'IDB Bali'],
            ['name' => 'Politeknik Dewantara', 'code' => 'POLIDEWA'],
            ['name' => 'Universitas Klabat', 'code' => 'UNKLAB'],
            ['name' => 'Universitas Kristen Indonesia Tomohon', 'code' => 'UKIT'],
            ['name' => 'Universitas Islam Negeri Sunan Kalijaga', 'code' => 'UIN Suka'],
            ['name' => 'Universitas Muhammadiyah Kendari', 'code' => 'UMKENDARI'],
            ['name' => 'Universitas Wijayakusuma Purwokerto', 'code' => 'UNWIKU'],
            ['name' => 'Universitas Nahdlatul Ulama Sulawesi Tenggara', 'code' => 'UNUSRA'],
            ['name' => 'Universitas 17 Agustus 1945 Surabaya', 'code' => 'UNTAG Surabaya'],
            ['name' => 'Universitas Winaya Mukti', 'code' => 'UNWIM'],
            ['name' => 'Universitas Ngurah Rai', 'code' => 'UNAR'],
            ['name' => 'Universitas Komputer Indonesia', 'code' => 'UNIKOM'],
            ['name' => 'Universitas Islam Negeri Alauddin Makassar', 'code' => 'UIN Alauddin'],
            ['name' => 'Universitas Tarumanagara', 'code' => 'UNTAR'],
            ['name' => 'Universitas Trisakti', 'code' => 'Usakti'],
            ['name' => 'Universitas Muhammadiyah Semarang', 'code' => 'UNIMUS'],
            ['name' => 'Universitas Persatuan Guru Republik Indonesia Semarang', 'code' => 'UPGRIS'],
            ['name' => 'Universitas Palangka Raya', 'code' => 'UPR'],
            ['name' => 'Universitas Negeri Surabaya', 'code' => 'UNESA'],
            ['name' => 'Universitas Andalas', 'code' => 'UNAND'],
            ['name' => 'Universitas Bung Hatta', 'code' => 'UBH'],
            ['name' => 'Universitas Muslim Indonesia', 'code' => 'UMI'],
            ['name' => 'Universitas Katolik Santo Thomas', 'code' => 'UNIKA Santo Thomas'],
            ['name' => 'Universitas Muhammadiyah Surabaya', 'code' => 'UM Surabaya'],
            ['name' => 'Universitas Pembangunan Panca Budi', 'code' => 'UNPAB'],
            ['name' => 'Universitas Islam Negeri Profesor Kiai Haji Saifuddin Zuhri Purwokerto', 'code' => 'UIN SAIZU'],
            ['name' => 'Universitas Negeri Semarang', 'code' => 'UNNES'],
            ['name' => 'Universitas Tanri Abeng', 'code' => 'TA UNIVERSITY'],
            ['name' => 'Politeknik Negeri Bengkalis', 'code' => 'POLBENG'],
            ['name' => 'Institut Teknologi Dan Bisnis Ahmad Dahlan Lamongan', 'code' => 'ITB ADL'],
            ['name' => 'Universitas Sriwijaya', 'code' => 'UNSRI'],
            ['name' => 'Universitas Tadulako', 'code' => 'UNTAD'],
            ['name' => 'Universitas Muhammadiyah Banjarmasin', 'code' => 'UMB'],
            ['name' => 'Universitas Katolik Widya Mandira Kupang', 'code' => 'UNWIRA'],
            ['name' => 'Universitas Kaltara', 'code' => 'UKALTARA'],
            ['name' => 'Universitas Muhammadiyah Jakarta', 'code' => 'UMJ'],
            ['name' => 'Politeknik Negeri Samarinda', 'code' => 'POLNES'],
            ['name' => 'Universitas Mercu Buana', 'code' => 'UMB'],
            ['name' => 'Universitas Gadjah Mada', 'code' => 'UGM'],
            ['name' => 'Universitas Budi Luhur', 'code' => 'UBL'],
            ['name' => 'Universitas Islam Negeri Ar-Raniry Banda Aceh', 'code' => 'UIN Ar-Raniry'],
            ['name' => 'Universitas Amikom Yogyakarta', 'code' => 'AMIKOM'],
            ['name' => 'Universitas Indraprasta PGRI', 'code' => 'UNINDRA'],
            ['name' => 'Universitas Pancasila', 'code' => 'UP'],
            ['name' => 'Institut Teknologi Nasional Malang', 'code' => 'ITN Malang'],
            ['name' => 'Universitas Pelita Bangsa', 'code' => 'UPB'],
            ['name' => 'Universitas Almuslim', 'code' => 'UMA'],
            ['name' => 'Universitas Widya Kartika', 'code' => 'UWIKA'],
            ['name' => 'Universitas Bengkulu', 'code' => 'UNIB'],
            ['name' => 'Universitas Pradita', 'code' => 'UP'],
            ['name' => 'Universitas Negeri Malang', 'code' => 'UM'],
            ['name' => 'Universitas Gorontalo', 'code' => 'UG'],
            ['name' => 'Universitas Bangka Belitung', 'code' => 'UBB'],
            ['name' => 'Institut Teknologi Indonesia', 'code' => 'ITI'],
            ['name' => 'Universitas Mahakarya Asia', 'code' => 'UNMAHA'],
            ['name' => 'Universitas Katolik Musi Charitas', 'code' => 'UKMC'],
            ['name' => 'Universitas Muhammadiyah Palembang', 'code' => 'UMP'],
            ['name' => 'Universitas Islam Zainul Hasan Genggong Probolinggo', 'code' => 'UNZAH Genggong'],
            ['name' => 'Universitas Halu Oleo', 'code' => 'UHO'],
            ['name' => 'Universitas Sains Alqur An', 'code' => 'UNSIQ'],
            ['name' => 'Universitas Aisyiyah Yogyakarta', 'code' => 'UNISA Yogyakarta'],
            ['name' => 'Universitas Khairun', 'code' => 'UNKHAIR'],
            ['name' => 'Universitas 17 Agustus 1945 Samarinda', 'code' => 'UNTAG Samarinda'],
            ['name' => 'Universitas Satyagama', 'code' => 'USA'],
            ['name' => 'Universitas Surakarta', 'code' => 'UNSA'],
            ['name' => 'Sekolah Tinggi Teknik Multimedia Internasional Malang', 'code' => 'STT Multimedia'],
            ['name' => 'Universitas Bosowa', 'code' => 'Ubos'],
            ['name' => 'Universitas Mataram', 'code' => 'UNRAM'],
            ['name' => 'Universitas Bung Karno', 'code' => 'UBK'],
            ['name' => 'Institut Teknologi Nasional Bandung', 'code' => 'ITENAS'],
            ['name' => 'Universitas Muhammadiyah Makassar', 'code' => 'UNISMUH'],
            ['name' => 'Universitas Pembangunan Nasional Veteran Jawa Timur', 'code' => 'UPN Veteran Jatim'],
            ['name' => 'Universitas PGRI Yogyakarta', 'code' => 'UPY'],
            ['name' => 'Universitas Pohuwato', 'code' => 'UNIPO'],
            ['name' => 'Universitas Sains Dan Teknologi Jayapura', 'code' => 'USTJ'],
            ['name' => 'Sekolah Tinggi Teknologi Cirebon', 'code' => 'STTC'],
            ['name' => 'Institut Teknologi Budi Utomo', 'code' => 'ITBU'],
            ['name' => 'Universitas Bumi Hijrah Tidore', 'code' => 'UNIBRAH'],
            ['name' => 'Universitas Adiwangsa Jambi', 'code' => 'UNAJA'],
            ['name' => 'Universitas Kebangsaan Republik Indonesia', 'code' => 'UKRI'],
            ['name' => 'Institut Teknologi Dan Bisnis Ahmad Dahlan', 'code' => 'ITB-AD'],
            ['name' => 'Universitas Pembangunan Jaya', 'code' => 'UPJ'],
            ['name' => 'Universitas Riau', 'code' => 'UNRI'],
            ['name' => 'Universitas Pendidikan Mandalika', 'code' => 'UNDIKMA'],
            ['name' => 'Universitas Dwijendra', 'code' => 'UNDWI'],
            ['name' => 'Universitas Ciputra Surabaya', 'code' => 'UC'],
            ['name' => 'Universitas Tanjungpura', 'code' => 'UNTAN'],
            ['name' => 'Universitas Mulawarman', 'code' => 'UNMUL'],
            ['name' => 'Sekolah Tinggi Teknik Malang', 'code' => 'STT Malang'],
            ['name' => 'Universitas Musamus Merauke', 'code' => 'UNMUS'],
            ['name' => 'Universitas Citra Bangsa', 'code' => 'UCB'],
            ['name' => 'Universitas Bandar Lampung', 'code' => 'UBL'],
            ['name' => 'Universitas Riau Kepulauan', 'code' => 'UNRIKA'],
            ['name' => 'Universitas Balikpapan', 'code' => 'UNIBA'],
            ['name' => 'Universitas Tompotika Luwuk Banggai', 'code' => 'UNTIKA'],
            ['name' => 'Universitas Flores', 'code' => 'UNIFLOR'],
            ['name' => 'Universitas Ichsan Sidenreng Rappang', 'code' => 'UNISAN Sidrap'],
            ['name' => 'Universitas Islam Negeri Maulana Malik Ibrahim Malang', 'code' => 'UIN Maliki'],
            ['name' => 'Universitas Cendekia Mitra Indonesia', 'code' => 'UCMI'],
            ['name' => 'Universitas Pertiwi', 'code' => 'UNPER'],
            ['name' => 'Politeknik Negeri Malang', 'code' => 'POLINEMA'],
            ['name' => 'Universitas Internasional Jakarta', 'code' => 'UNIJA'],
            ['name' => 'Institut Seni Indonesia Yogyakarta', 'code' => 'ISI Yogyakarta'],
            ['name' => 'Universitas Sains Indonesia', 'code' => 'USI'],
            ['name' => 'Universitas Muhammadiyah Tegal', 'code' => 'UMT'],
            ['name' => 'Institut Seni Indonesia Denpasar', 'code' => 'ISI Denpasar'],
            ['name' => 'Universitas Telkom', 'code' => 'TEL-U'],
            ['name' => 'Universitas Informatika Dan Bisnis Indonesia', 'code' => 'UNIBI'],
            ['name' => 'Universitas Surabaya', 'code' => 'UBAYA'],
            ['name' => 'Politeknik Kreatif Indonesia', 'code' => 'Polkrefindo'],
            ['name' => 'Universitas Negeri Padang', 'code' => 'UNP'],
            ['name' => 'Universitas Widyatama', 'code' => 'UTAMA'],
            ['name' => 'Universitas Wiraraja', 'code' => 'UNIVIRA'],
            ['name' => 'Universitas PGRI Silampari', 'code' => 'UNPIR'],
            ['name' => 'Akademi Kesejahteraan Sosial AKK', 'code' => 'AKK'],
            ['name' => 'Universitas Dinamika', 'code' => 'UNDIKA'],
            ['name' => 'Politeknik TEDC', 'code' => 'POLTEK TEDC'],
            ['name' => 'Institut Bisnis Dan Teknologi Indonesia', 'code' => 'INSTIKI'],
            ['name' => 'Universitas Bhinneka Nusantara', 'code' => 'UBN'],
            ['name' => 'Universitas Sahid Surakarta', 'code' => 'USAP'],
            ['name' => 'Politeknik Seni Yogyakarta', 'code' => 'POLTEKSENI'],
            ['name' => 'Universitas Negeri Jakarta', 'code' => 'UNJ'],
            ['name' => 'Universitas Teknologi Digital', 'code' => 'UTD'],
            ['name' => 'Universitas Trilogi', 'code' => 'TRILOGI'],
            ['name' => 'Institut Seni Budaya Indonesia Aceh', 'code' => 'ISBI Aceh'],
            ['name' => 'Politeknik Tempo', 'code' => 'POLTEM'],
            ['name' => 'Institut Informatika Indonesia Surabaya', 'code' => 'III Surabaya'],
            ['name' => 'Institut Teknologi Sains Bandung', 'code' => 'ITSB'],
            ['name' => 'Institut Seni Budaya Indonesia Bandung', 'code' => 'ISBI Bandung'],
            ['name' => 'Institut Komunikasi Dan Bisnis LSPR', 'code' => 'LSPR'],
            ['name' => 'Universitas Mulia', 'code' => 'UNI MULA'],
            ['name' => 'Universitas Fort De Kock', 'code' => 'UFD KOCK'],
            ['name' => 'Institut Informatika Dan Bisnis Darmajaya', 'code' => 'IIB Darmajaya'],
            ['name' => 'Universitas Bina Insani', 'code' => 'UNI BI'],
            ['name' => 'Universitas Tiga Serangkai', 'code' => 'UTISA'],
            ['name' => 'Universitas Ibn Khaldun Bogor', 'code' => 'UIKA Bogor'],
            ['name' => 'Sekolah Tinggi Teknologi Muhammadiyah AR Fachruddin', 'code' => 'STTM Ar Fachruddin'],
            ['name' => 'Institut Teknologi Dan Bisnis Tuban', 'code' => 'ITB Tuban'],
            ['name' => 'Universitas Dian Nuswantoro', 'code' => 'UDINUS'],
            ['name' => 'Universitas Sampoerna', 'code' => 'US'],
            ['name' => 'Universitas Esa Unggul', 'code' => 'UEU'],
            ['name' => 'Universitas Multi Data Palembang', 'code' => 'UMDP'],
            ['name' => 'Universitas Adzkia', 'code' => 'UA'],
            ['name' => 'Universitas Islam Negeri Syekh Ali Hasan Ahmad Addary Padangsidimpuan', 'code' => 'UIN Syekh Ali Hasan'],
            ['name' => 'Universitas Satu', 'code' => 'USATU'],
            ['name' => 'Politeknik Bali Maha Werdhi', 'code' => 'POLTEKBW'],
            ['name' => 'Universitas Al Hikmah Jepara', 'code' => 'UAH'],
            ['name' => 'Universitas Awal Bros', 'code' => 'UAB'],
            ['name' => 'Universitas Primakara', 'code' => 'UP'],
            ['name' => 'Politeknik Negeri Jakarta', 'code' => 'PNJ'],
            ['name' => 'Institut Teknologi Dan Bisnis Kristen Bukit Pengharapan', 'code' => 'ITB KPBP'],
            ['name' => 'Akademi Kesejahteraan Sosial Ibu Kartini', 'code' => 'AKSIK'],
            ['name' => 'Institut Teknologi Dan Bisnis Palcomtech', 'code' => 'ITB Palcomtech'],
            ['name' => 'Institut Teknologi Telkom Purwokerto', 'code' => 'ITTP'],
            ['name' => 'Institut Sains Dan Teknologi Terpadu Surabaya', 'code' => 'ISTTS'],
            ['name' => 'Institut Teknologi Dan Bisnis Kalbis', 'code' => 'KALBIS Institute'],
            ['name' => 'Universitas Maarif Hasyim Latif', 'code' => 'UMAHA'],
            ['name' => 'Universitas Syekh Yusuf Al Makassari Gowa', 'code' => 'UNSYAM'],
            ['name' => 'Universitas Metamedia', 'code' => 'UMET'],
            ['name' => 'Universitas Ngudi Waluyo', 'code' => 'UNW'],
            ['name' => 'Universitas Hindu Negeri I Gusti Bagus Sugriwa Denpasar', 'code' => 'UHN I Gusti Bagus Sugriwa'],
            ['name' => 'Universitas Pendidikan Ganesha', 'code' => 'UNDIKSHA'],
            ['name' => 'Universitas Swadaya Gunung Djati', 'code' => 'UNSWAGATI'],
            ['name' => 'Sekolah Tinggi Desain Indonesia Bandung', 'code' => 'STDI'],
            ['name' => 'Institut Kesenian Jakarta', 'code' => 'IKJ'],
            ['name' => 'Universitas Wanita Internasional', 'code' => 'UWI'],
            ['name' => 'Universitas Bumigora', 'code' => 'UNIGORA'],
            ['name' => 'Universitas Indonesia Mandiri', 'code' => 'UIM'],
            ['name' => 'Universitas LIA', 'code' => 'UNIL'],
            ['name' => 'Universitas Putra Indonesia Yptk Padang', 'code' => 'UPI YPTK'],
            ['name' => 'Universitas Teknologi Bandung', 'code' => 'UTB'],
            ['name' => 'Universitas Catur Insan Cendekia', 'code' => 'UCIC'],
            ['name' => 'Universitas Pasundan', 'code' => 'UNPAS'],
            ['name' => 'Institut Teknologi Dan Bisnis Asia Malang', 'code' => 'ITB Asia'],
            ['name' => 'STMIK Amik Bandung', 'code' => 'STMIK-AMIK'],
            ['name' => 'Institut Seni Indonesia Padang Panjang', 'code' => 'ISI Padang Panjang'],
            ['name' => 'Universitas Nahdlatul Ulama Pasuruan', 'code' => 'UNU Pasuruan'],
            ['name' => 'Institut Filsafat Dan Teknologi Kreatif Ledalero', 'code' => 'IFTK Ledalero'],
            ['name' => 'Sekolah Tinggi Desain LaSalle', 'code' => 'LaSalle College'],
            ['name' => 'Universitas Potensi Utama', 'code' => 'UP'],
            ['name' => 'Universitas Ma Chung', 'code' => 'UNIMAC'],
            ['name' => 'Universitas Sains Dan Teknologi Komputer', 'code' => 'STEKOM'],
            ['name' => 'Universitas Internasional Semen Indonesia', 'code' => 'UISI'],
            ['name' => 'Universitas Bunda Mulia', 'code' => 'UBM'],
            ['name' => 'Universitas Kalbis', 'code' => 'KALBIS University'],
            ['name' => 'Universitas PGRI Jombang', 'code' => 'UNIP'],
            ['name' => 'Universitas Hayam Wuruk Perbanas', 'code' => 'UHW Perbanas'],
            ['name' => 'Universitas Muhammadiyah Purwokerto', 'code' => 'UMP'],
            ['name' => 'Universitas Nusa Putra', 'code' => 'UNSAP'],
            ['name' => 'Universitas Nahdlatul Ulama Sidoarjo', 'code' => 'UNUSIDA'],
            ['name' => 'Universitas Prasetiya Mulya', 'code' => 'Prasmul'],
            ['name' => 'Universitas Aufa Royhan', 'code' => 'UAR'],
            ['name' => 'Politeknik Bina Madani', 'code' => 'POLTEKBIMA'],
            ['name' => 'Akademi Seni Rupa Dan Desain MSD', 'code' => 'ASRIDE MSD'],
            ['name' => 'Universitas Paramadina', 'code' => 'PARAMADINA'],
            ['name' => 'Sekolah Tinggi Seni Rupa Dan Desain Visi Indonesia', 'code' => 'STSRD Visi'],
            ['name' => 'Institut Sains Dan Teknologi Al-Kamal', 'code' => 'ISTN'],
            ['name' => 'Institut Seni Budaya Indonesia Tanah Papua', 'code' => 'ISBI Tanah Papua'],
            ['name' => 'Universitas Islam Nahdlatul Ulama Jepara', 'code' => 'UNISNU'],
            ['name' => 'Institut Teknologi Dan Bisnis Stikom Ambon', 'code' => 'ITB Stikom Ambon'],
            ['name' => 'Universitas Muhammadiyah Tangerang', 'code' => 'UMT'],
            ['name' => 'Politeknik Harapan Bersama', 'code' => 'POLTEK HARBER'],
            ['name' => 'Politeknik Negeri Media Kreatif', 'code' => 'POLIMEDIA'],
            ['name' => 'Politeknik Perkapalan Negeri Surabaya', 'code' => 'PPNS'],
            ['name' => 'Sekolah Tinggi Desain Interstudi', 'code' => 'STDI Interstudi'],
            ['name' => 'Sekolah Tinggi Media Komunikasi Trisakti', 'code' => 'STMK Trisakti'],
            ['name' => 'Akademi Seni Dan Desain Indonesia Surakarta', 'code' => 'ASDI Surakarta'],
            ['name' => 'Institut Sains Dan Teknologi Td Pardede', 'code' => 'ISTP'],
            ['name' => 'Universitas Aisyiyah Bandung', 'code' => 'UNISA Bandung'],
            ['name' => 'Universitas Kristen Satya Wacana', 'code' => 'UKSW'],
            ['name' => 'Politeknik Sains Seni Rekakreasi', 'code' => 'PSS Reka Kreasi'],
            ['name' => 'Institut Teknologi Harapan Bangsa', 'code' => 'ITHB'],
            ['name' => 'Institut Teknologi Dan Sains Nahdlatul Ulama Pasuruan', 'code' => 'ITSNU Pasuruan'],
            ['name' => 'Institut Manajemen Wiyata Indonesia', 'code' => 'IMWI'],
            ['name' => 'Politeknik Industri Furnitur Dan Pengolahan Kayu', 'code' => 'POLIFURNI'],
            ['name' => 'Institut Teknologi Batam', 'code' => 'ITEBA'],
            ['name' => 'Akademi Teknik PIKA', 'code' => 'AT PIKA'],
            ['name' => 'Universitas Adhirajasa Reswara Sanjaya', 'code' => 'UNJAYA'],
            ['name' => 'Universitas Kuningan', 'code' => 'UNIKU'],
            ['name' => 'Universitas Teknologi Indonesia', 'code' => 'UTI'],
            ['name' => 'Politeknik Muhammadiyah Tegal', 'code' => 'POLMUTECH'],
            ['name' => 'STIKI Malang', 'code' => 'STIKI'],
            ['name' => 'Akademi Seni Rupa Dan Desain ISWI Jakarta', 'code' => 'ASRDI ISWI'],
            ['name' => 'STKIP Pangeran Antasari', 'code' => 'STKIP PA'],
            ['name' => 'Universitas Multimedia Nusantara', 'code' => 'UMN'],
            ['name' => 'Sekolah Tinggi Teknologi Bandung', 'code' => 'STT Bandung'],
            ['name' => 'Politeknik Internasional Bali', 'code' => 'PIB'],
            ['name' => 'Institut Sains Dan Teknologi Muhammadiyah Tarakan', 'code' => 'ISTM Tarakan'],
            ['name' => 'Universitas Nahdlatul Ulama Maluku Utara', 'code' => 'UNUT'],
            ['name' => 'Universitas Muhammadiyah Jambi', 'code' => 'UM Jambi'],
            ['name' => 'Universitas Muhammadiyah Palopo', 'code' => 'UM Palopo'],
            ['name' => 'Universitas Sintuwu Maroso Poso', 'code' => 'UNSIMAR'],
            ['name' => 'Institut Teknologi Nasional Yogyakarta', 'code' => 'ITNY'],
            ['name' => 'Universitas Jember', 'code' => 'UNEJ'],
            ['name' => 'Universitas Muhammadiyah Pare-pare', 'code' => 'UMPAR'],
            ['name' => 'Universitas Simalungun', 'code' => 'USI'],
            ['name' => 'Universitas Muhammadiyah Barru', 'code' => 'UMBAR'],
            ['name' => 'Universitas Islam Sultan Agung', 'code' => 'UNISSULA'],
            ['name' => 'Universitas Muhammadiyah Sorong', 'code' => 'UMSOR'],
            ['name' => 'Universitas Muhammadiyah Mataram', 'code' => 'UMMAT'],
            ['name' => 'Universitas Jenderal Soedirman', 'code' => 'UNSOED'],
            ['name' => 'Politeknik Pariwisata Medan', 'code' => 'POLTEKPAR Medan'],
            ['name' => 'Politeknik Negeri Bali', 'code' => 'PNB'],
            ['name' => 'Universitas PGRI Adi Buana', 'code' => 'UNIPA Surabaya'],
            ['name' => 'Universitas Maritim Raja Ali Haji', 'code' => 'UMRAH'],
            ['name' => 'Universitas Mahasaraswati Denpasar', 'code' => 'UNMAS'],
            ['name' => 'Universitas Hindu Indonesia', 'code' => 'UNHI'],
            ['name' => 'Institut Pariwisata Dan Bisnis Internasional', 'code' => 'IPBI'],
            ['name' => 'Universitas Sulawesi Barat', 'code' => 'UNSULBAR'],
            ['name' => 'Politeknik Pariwisata NHI Bandung', 'code' => 'POLTEKPAR NHI'],
            ['name' => 'Universitas Muhammadiyah Sinjai', 'code' => 'UMSINJAI'],
            ['name' => 'Universitas Pakuan', 'code' => 'UNPAK'],
            ['name' => 'Universitas Islam Bandung', 'code' => 'UNISBA'],
            ['name' => 'Universitas Islam Riau', 'code' => 'UIR'],
            ['name' => 'Institut Teknologi Dan Bisnis Karya Pembangunan Papua', 'code' => 'ITB KAPP'],
            ['name' => 'Politeknik Pariwisata Batam', 'code' => 'POLTEKPAR Batam'],
            ['name' => 'Politeknik Negeri Padang', 'code' => 'PNP'],
            ['name' => 'Universitas Muhammadiyah Berau', 'code' => 'UMB'],
            ['name' => 'Universitas Islam Kuantan Singingi', 'code' => 'UNIKS'],
            ['name' => 'Universitas Terbuka', 'code' => 'UT'],
            ['name' => 'Universitas Muhammadiyah Bulukumba', 'code' => 'UM Bulukumba'],
            ['name' => 'Universitas Sali Al-Aitaam', 'code' => 'USA'],
            ['name' => 'Universitas Batam', 'code' => 'UNIBA'],
            ['name' => 'Universitas Cenderawasih', 'code' => 'UNCEN'],
            ['name' => 'Universitas Pattimura', 'code' => 'UNPATTI'],
            ['name' => 'Universitas Amal Ilmiah Yapis Wamena', 'code' => 'UNAIM'],
            ['name' => 'Universitas Semarang', 'code' => 'USM'],
            ['name' => 'Universitas Lakidende Unahaa', 'code' => 'UNILAKI'],
            ['name' => 'Universitas Karimun', 'code' => 'UK'],
            ['name' => 'Universitas Teknologi Sulawesi Utara', 'code' => 'UTSU'],
            ['name' => 'Universitas Karyadarma Kupang', 'code' => 'UNDARMA'],
            ['name' => 'Institut Teknologi Yogyakarta', 'code' => 'ITY'],
            ['name' => 'Universitas Al-Muslim', 'code' => 'UMA'],
            ['name' => 'Universitas Bojonegoro', 'code' => 'UNIRO'],
            ['name' => 'Universitas Caritas Indonesia', 'code' => 'UCAR'],
            ['name' => 'Universitas Dumoga Kotamobagu', 'code' => 'UDK'],
            ['name' => 'Universitas Ibn Khaldun', 'code' => 'UIKA'],
            ['name' => 'Universitas Islam Negeri Antasari Banjarmasin', 'code' => 'UIN Antasari'],
            ['name' => 'Universitas Islam Negeri Raden Mas Said Surakarta', 'code' => 'UIN Raden Mas Said'],
            ['name' => 'Universitas Ivet', 'code' => 'UNIVET'],
            ['name' => 'Universitas Jambi', 'code' => 'UNJA'],
            ['name' => 'Universitas Muhammadiyah Madiun', 'code' => 'UMMAD'],
            ['name' => 'Universitas Muhammadiyah Papua', 'code' => 'UM Papua'],
            ['name' => 'Universitas Musi Rawas', 'code' => 'UNMURA'],
            ['name' => 'Universitas Padjadjaran', 'code' => 'UNPAD'],
            ['name' => 'Universitas Papua', 'code' => 'UNIPA'],
            ['name' => 'Universitas Persatuan Islam', 'code' => 'UPI'],
            ['name' => 'Universitas Serasan', 'code' => 'UNSER'],
            ['name' => 'Universitas Wira Bhakti', 'code' => 'UWB'],
            ['name' => 'Institut Teknologi Dan Bisnis Maritim Balik Diwa', 'code' => 'ITBM Balik Diwa'],
            ['name' => 'Politeknik Ahli Usaha Perikanan', 'code' => 'POLTEK AUP'],
            ['name' => 'Politeknik Negeri Ambon', 'code' => 'POLNAM'],
            ['name' => 'Politeknik Negeri Lampung', 'code' => 'POLINELA'],
            ['name' => 'Sekolah Tinggi Teknologi Kelautan Balik Diwa', 'code' => 'STTK Balik Diwa'],
            ['name' => 'Universitas Halmahera', 'code' => 'UNIERA'],
            ['name' => 'Universitas HKBP Nommensen Pematangsiantar', 'code' => 'UHN Pematangsiantar'],
            ['name' => 'Universitas Panca Bhakti', 'code' => 'UPB'],
            ['name' => 'Universitas Serambi Mekkah', 'code' => 'USM'],
            ['name' => 'Universitas Trunojoyo', 'code' => 'UTM'],
            ['name' => 'Universitas Al-azhar Indonesia', 'code' => 'UAI'],
            ['name' => 'Universitas Muhammadiyah Bangka Belitung', 'code' => 'UMBB'],
            ['name' => 'Universitas Teknologi Sumbawa', 'code' => 'UTS'],
            ['name' => 'Politeknik Pertanian Negeri Samarinda', 'code' => 'POLITANI Samarinda'],
        ];

        $timestamp = Carbon::now();

        foreach ($universities as &$university) {
            // Tambahkan email dari mapping
            $university['email'] = $emailMapping[$university['name']] ?? '-';
            $university['created_at'] = $timestamp;
            $university['updated_at'] = $timestamp;
        }

        // Insert hanya jika belum ada
        foreach ($universities as $university) {
            DB::table('universities')->updateOrInsert(
                ['name' => $university['name']],
                $university
            );
        }
        */ // End comment - data universitas tidak digunakan
    }
}
