name: Beta Deployment

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Prepare deployment files
        run: |
          mkdir -p .deploy
          rsync -a ./ .deploy/ \
            --exclude=".deploy/" \
            --exclude="vendor/" \
            --exclude=".vscode/" \
            --exclude="public/assets/plugins/" \
            --exclude="public/gs/" \
            --exclude=".git/" \
            --exclude="node_modules/"

      - name: Sync files using SFTP
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 2222
          source: ".deploy"
          target: "/home/ubuntu/daisy/daisy"
          overwrite: true
          rm: false
          strip_components: 1
