name: Beta SP3STAB Deployment

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Sync files using SFTP
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SFTP_SP3STAB_SERVER }}
          username: ${{ secrets.SFTP_SP3STAB_USERNAME }}
          password: ${{ secrets.SFTP_SP3STAB_PASSWORD }}
          port: 22
          source: "."
          target: "/var/www/sipenahana/daisy"
          overwrite: true
          rm: false
          exclude: '["vendor/**", ".vscode/**", "public/assets/plugins/**", "public/gs/**", ".git/**", "node_modules/**"]'
