name: Beta Dev Deployment

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Sync files using SFTP
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 2222
          source: "."
          target: "/home/ubuntu/daisy/daisy-dev"
          overwrite: true
          rm: false
          exclude: '["vendor/**", ".vscode/**", "public/assets/plugins/**", "public/gs/**", ".git/**", "node_modules/**"]'
